=== bogeo/suspatterns/plml/plml_bo-2.0.xsd
<?xml version="1.0" ?>
<!--- PLML extended version BO-2.0 from https://github.com/bogeo/suspatterns/plml/plml_bo-2.0.xsd. --> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pattern">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="1" minOccurs="1" name="name" type="xsd:string"/>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="alias" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="illustration"/>
				<xsd:element maxOccurs="1" minOccurs="1" name="problem" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="context" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="forces"/>
				<xsd:element maxOccurs="1" minOccurs="1" name="solution"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="synopsis" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="diagram">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="location" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="evidence">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="example"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="rationale"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="confidence" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="literature">
					<xsd:annotation>
						<xsd:documentation>Opposite to PLML 1.1, literature will be given separate ref elements here</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="ref">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="id" type="xsd:string" use="optional"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="implementation"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="formalization">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="participant">
								<xsd:annotation>
									<xsd:documentation>Optional listing of pattern participants</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="identifier" type="xsd:string" use="required"/>
											<xsd:attribute name="type" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="source-code">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="location" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="language" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="related-patterns">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="pattern-link">
								<xsd:annotation>
									<xsd:documentation>Pre-defined PLML relation type</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="type" type="xsd:string" use="required"/>
											<xsd:attribute name="patternID" type="xsd:integer" use="required"/>
											<xsd:attribute name="collection" type="xsd:string" use="required"/>
											<xsd:attribute name="label" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="management">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="0" name="author" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="revision-number" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="creation-date" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="last-modified" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="credits" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="patternID" type="xsd:integer"/>
			<xsd:attribute name="collection" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== bogeo/suspatterns/descriptions/ReactiveResponse.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.1.css"?>
<pattern patternID="15" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Reactive Response</name>
	<alias></alias>
	<problem>
		TODO This pattern has not been documented yet. See given literature [1]
		for details. 
	</problem>
	<solution>
	</solution>
	<evidence>
		<rationale>
		</rationale>
	</evidence>
	<confidence>Idea</confidence>
	<literature>
		<bibliomixed id="1">
			Geiger et al. (2020): Ressourceneffiziente Programmierung. Berlin: Bitkom, S. 13. 
		</bibliomixed>
	</literature>
	
	<related-patterns>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>12.05.2021</creation-date>
		<last-modified>12.05.2021</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/BackwardCompatibility.xml
<?xml version="1.0" ?>s
<pattern patternID="6" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Backward Compatibility</name>
	<problem>
		A new software release does not run on the computer currently used. 
	</problem>
	<solution>
		The software producer ensures that the new software release runs on the 
		old machine. Since ICT permanently undergoes evelutionary developments,  
		it will be hard to ensure this. - However, this gives more a 
		postulation than a software design pattern. Maybe in the future we 
		can identify some concrete patterns which allow to achieve this goal. 
		Some clues could be provided by a formal description (what still is a 
		ToDo; however, the system to be described formally could include 
		product stakeholders such as the user or product managers as well  
		as the machine which might become obsolescent or system-internal 
		interfaces as participants).
	</solution>
	<literature>
	 	Kern, E.; Dick, M.; Naumann, S.; Filler, A. (2015): Labelling Sustainable Software Products and Websites. 3rd Intern. Conf. on ICT for Sustainability (ICT4S 2015) / EnviroInfo 2015, pp. 82-91. 
 	</literature>
	<formalization/>
	<related-patterns>
		<pattern-link type="related-to" 
			patternID="7" collection="candidates" label="component replaceability"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>14.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/SustainabilityAwareness.xml
<?xml version="1.0" ?>
<pattern patternID="99" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Sustainability Awareness</name>
	<alias>Psi increase</alias>
	<problem>
		Some stakeholders (here: software users, software developers, 
		product managers, software operators, etc.) do not yet care about 
		sustainability issues. The reasons for this are manifold, e.g. 
		missing sustainability knowledge.
	</problem>
	<solution>
		Sensitize the stakeholders for this topic by raising awareness 
		about software sustainability issues. E.g., this can be done by making
		relevant software concepts transparent for the general public. Since
		the interaction between human stakeholders and the software plays
		an important role, this strategic approach has been registered as 
		pattern candidate here.
	</solution>
	<literature>
	 	Schmidt, B.; Wytzisk, A. (2019): Nachhaltigkeitsaspekte in der 
		Softwareentwicklung. In: Englert, M.; Ternes, A. (eds.): Nachhaltiges
		Management. Berlin: Springer, pp. 651-668.
 	</literature>
	<formalization/>
	<related-patterns>
		<pattern-link type="contains" 
			patternID="1" collection="candidates" label="compensate"/>
		<pattern-link type="contains" 
			patternID="3" collection="candidates" label="open source"/>
		<pattern-link type="contains" 
			patternID="4" collection="candidates" label="standby"/>
		<pattern-link type="contains" 
			patternID="5" collection="candidates" label="component leaflets"/>
		<pattern-link type="contains" 
			patternID="6" collection="candidates" label="backward compatibility"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>14.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/BufferedDataflow.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="12" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Buffered Dataflow</name>
	<alias>Minimize Dataflow</alias>
	<problem>
		Factors such as CPU time and memory consumption influence the energy consumption 
		at software runtime. Moving data (e.g. from memory to hard drive or via the network) is 
		an activity that might consume a lot of energy. (See [1].) 
	</problem>
	<solution>
		Often it is a good idea, to work with caches or buffers to keep the the data flow generally low.
	</solution>
	<evidence>
		<rationale>
		</rationale>
	</evidence>
	<confidence>Idea</confidence>
	<literature>
		<bibliomixed id="1">
			Geiger et al. (2020): Ressourceneffiziente Programmierung. Berlin: Bitkom, S. 9. 
		</bibliomixed>
	</literature>
	<related-patterns>
		<pattern-link type="is-related-to" patternID="2" collection="candidates" label="don't stream twice"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>12.05.2021</creation-date>
		<last-modified>12.05.2021</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/DontStreamTwice.xml
<?xml version="1.0" ?>
<pattern patternID="2" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Don't Stream Twice</name>
	<alias>Cache Streamed Document</alias>
	<problem>
		Often streamable Web content is accessed twice. Thus, unnecessarily
		Internet traffic is induced. The consequences are manifold: This
		data transfer costs electric energy (Web-server, Web-client, and
		transmission). Moreover, on the user side, data volume my be consumed.
	</problem>
	<solution>
		Store the streamed content in a cache on the user's local computer.
	</solution>
	<formalization language="CafeOBJ" location="DontStreamTwice.cafe"/>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>08.07.2019</creation-date>
		<last-modified>08.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/Standby.xml
<?xml version="1.0" ?>
<pattern patternID="4" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Standby Operation</name>
	<alias>Sleep Mode</alias>
	<alias>Suspend</alias>
	<problem>
		The computer supplying software components consumes electric energy 
		although no software is in use.
	</problem>
	<solution>
		Let the computer enter a sleep state, i.e. pause the state of the 
		machine. When restored, the operation continues from the same point,
		offering the same applications, having the same files open, being in
		exactly in the same state as when paused. 
	</solution>
	<evidence>
		<rationale>
			Basically, there will be some controversy as to whether this is a 
			sustainability pattern or whether just energy efficiency is 
			increased. However, implementation of this "pattern" might raise
			sustainability awareness (see related pattern).
		</rationale>
	</evidence>
	<formalization language="CafeOBJ">
		<participant identifier="sys" type="uml$Executable"/>	
  		<participant identifier="freezer" type="op freeze : uml$Executable -> uml$Executable"/>
		<participant identifier="waker" type="wakeup : uml$Executable -> uml$Executable"/>	
		<participant identifier="checker" type="exceedIdleTime : uml$Executable -> uml$Executable"/>	
  		<source-code location="Standby.cafe"/>
	</formalization>
	<related-patterns>
		<pattern-link type="related-to" patternID="99" collection="candidates" 
			label="raise sustainability awareness"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.3</revision-number>
		<creation-date>12.07.2019</creation-date>
		<last-modified>16.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/Compensate.xml
<?xml version="1.0" ?>
<pattern patternID="1" collection="candidates" xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Compensate</name>
	<alias>Regenerative operation</alias>
	<problem>
		Software operation consumes electric energy. Now the carbon dioxide emission that is induced by the operation of the software shall be reduced.
	</problem>
	<solution>
		Reduce the share of consumed fossil energy by suitable compensation measures and assert these measures indeed will be implemented.
	</solution>
	<diagram location="Compensate.jpg"/>
	<literature>
	 	Schmidt, B. (2019): Towards a Formal Language to Describe Sustainable Software Patterns. Bochum: University of Applied Sciences. Submitted paper.
 	</literature>
	<formalization language="CafeOBJ" location="Compensate.pat"/>
	<related-patterns>
		<pattern-link type="related-to" patternID="99" collection="candidates" label="increase awareness"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.2</revision-number>
		<creation-date>01.07.2019</creation-date>
		<last-modified>08.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/Uninstall.xml
<?xml version="1.0" ?>
<pattern patternID="3" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Uninstall</name>
	<alias>Removability</alias>
	<problem>
		A software that is no longer needed takes memory and might have 
		negative impact on the computer's performance.
	</problem>
	<solution>
		Prove an uninstaller. Ideally, the software can be removed completely
		from the computer (inclusively data, configuration files etc.). User 
		support should be given explicitly. 
	</solution>
	<evidence>
		<rationale>
			After deinstallation of the software, released memory can be used
			by other software or data. 
		</rationale>
	</evidence>
	<literature>
		<ref id="1">
			Umweltbundesamt, eds. (2017): Kriterienkatalog f√ºr nachhaltige 
			Software, Project UFOPLAN FKZ-Nr. 3715 37 601 0, Berlin: Federal 
			Environment Agency.
		</ref>
		<ref id="2">
			Umweltbundesamt, eds.: Project REFOPLAN. Berlin: Federal 
			Environment Agency, work in progress.
		</ref>
 	</literature>
	<formalization language="CafeOBJ">
  		<source-code location=""/>
	</formalization>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>14.07.2019</last-modified>
	</management>
</pattern>
