=== bogeo/suspatterns/plml/plml_bo-2.0.xsd
<?xml version="1.0" ?>
<!--- PLML extended version BO-2.0 from https://github.com/bogeo/suspatterns/plml/plml_bo-2.0.xsd. --> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pattern">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="1" minOccurs="1" name="name" type="xsd:string"/>
				<xsd:element maxOccurs="unbounded" minOccurs="0" name="alias" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="illustration"/>
				<xsd:element maxOccurs="1" minOccurs="1" name="problem" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="context" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="forces"/>
				<xsd:element maxOccurs="1" minOccurs="1" name="solution"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="synopsis" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="diagram">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="location" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="evidence">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="example"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="rationale"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="confidence" type="xsd:string"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="literature">
					<xsd:annotation>
						<xsd:documentation>Opposite to PLML 1.1, literature will be given separate ref elements here</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="ref">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="id" type="xsd:string" use="optional"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="implementation"/>
				<xsd:element maxOccurs="1" minOccurs="0" name="formalization">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="participant">
								<xsd:annotation>
									<xsd:documentation>Optional listing of pattern participants</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="identifier" type="xsd:string" use="required"/>
											<xsd:attribute name="type" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="source-code">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="location" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="language" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="related-patterns">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="unbounded" minOccurs="0" name="pattern-link">
								<xsd:annotation>
									<xsd:documentation>Pre-defined PLML relation type</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="type" type="xsd:string" use="required"/>
											<xsd:attribute name="patternID" type="xsd:integer" use="required"/>
											<xsd:attribute name="collection" type="xsd:string" use="required"/>
											<xsd:attribute name="label" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element maxOccurs="1" minOccurs="0" name="management">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element maxOccurs="1" minOccurs="0" name="author" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="revision-number" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="creation-date" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="last-modified" type="xsd:string"/>
							<xsd:element maxOccurs="1" minOccurs="0" name="credits" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="patternID" type="xsd:integer"/>
			<xsd:attribute name="collection" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== bogeo/suspatterns/descriptions/OpenSource.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="8" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Open Source</name>
	<alias>Repair</alias>
	<problem>
		A software lacks functionality or can not be used anymore since the 
		technical environment changed or since there simply is a bug in it which
		the software producer will not fix.
	</problem>
	<solution>
		Make available the source code to enable the user to extend or repair the 
		software. This requires that the user has the technical skills and know-how 
		to change the software as well as a suitable build environment.
	</solution>
	<evidence>
		<rationale>
			Implementation of this "pattern" might raise sustainability awareness 
			(see related pattern candidate). Thus, this pattern seems to refer to 
			the concept of "strong sustainability" (Martens & Schilder 2013), but
			this remains to be discussed in further detail: How and to which extent
			does the Open Source philosophy contribute to the goals of sustainable
			development? (And: Is it really a "pattern"?)
		</rationale>
	</evidence>
	<confidence>Idea</confidence>
	<literature>
		<bibliomixed id="1">
			Busch, T. (2008): Open Source und Nachhaltigkeit. Open Source Jahrbuch 
			2008, TU Berlin.
		</bibliomixed>
	</literature>
	<formalization language="CafeOBJ">
  		<participant identifier="user" type="User &lt; uml$Actor"/>
		<participant identifier="env" type="BuildEnv"/>	
		<participant identifier="code" type="uml$Source"/>	
		<participant identifier="softw" type="uml$Executable"/>	
  		<source-code location="OpenSource.cafe"/>
	</formalization>
	<related-patterns>
		<pattern-link type="is-contained-by" 
			patternID="99" collection="candidates" 
			label="raise sustainability awareness"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.4</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>12.06.2021</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/OutsourceGeneralComputations.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="13" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Outsource General Computations</name>
	<alias>Decoupled Components</alias>
	<problem>
		A recurring, computationally intensive task (for example the evening analysis of all sales 
		results of a supermarket chain) increases the hardware requirements for the overall system 
		in which it is performed. If the system is otherwise not very computationally intensive, there 
		will be an avoidable energy loss since the hardware is geared towards this edge-case. [1]
	</problem>
	<solution>
		Release such a task into its own (e.g. containerized) environment that will be available 
		at execution time of the task only. This can save a large amount of energy. The actual system 
		and thus the hardware to be operated continuously becomes smaller and more efficient.
	</solution>
	<evidence>
		<rationale>
		</rationale>
	</evidence>
	<confidence>reviewed</confidence>
	<literature>
		<bibliomixed id="1">
			Geiger et al. (2020): Ressourceneffiziente Programmierung. Berlin: Bitkom, S. 12. 
		</bibliomixed>
	</literature>
	<related-patterns>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>12.05.2021</creation-date>
		<last-modified>12.05.2021</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/PostponeIntoGreenPhase.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.1.css"?>
<pattern patternID="10" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Postpone Into Green Phase</name>
	<alias></alias>
	<problem>
		It is a general aim is to enable users to use energy in a way that conserves 
		resources. However, the application used does not know how the energy it 
		consumes has been generated (e.g. regenerative or not). 
(See [1].)
	</problem>
	<solution>
		Offer the software application the possibility to carry of not urgently needed 
		operations when green electricity is available. (E.g., postpone computationally 
		intensive computations, where possible.) For this purpose, a component must 
		be provided which provides information about the way in which the currently 
		available energy has been generated.
	</solution>
	<evidence>
		<rationale>
		</rationale>
	</evidence>
	<confidence>Idea</confidence>
	<literature>
		<bibliomixed id="1">
			Geiger et al. (2020): Ressourceneffiziente Programmierung. Berlin: Bitkom, S. 9. 
		</bibliomixed>
	</literature>
	<related-patterns>
		<pattern-link type="is-related-to" patternID="1" collection="candidates" label="compensate energy consumption"/>
		<pattern-link type="is-related-to" patternID="11" collection="candidates" label="switch off unneeded features"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>12.05.2021</creation-date>
		<last-modified>12.05.2021</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/ComponentLeaflets.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="5" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Component Leaflets</name>
	<alias>Sustainable Parts</alias>
	<problem>
		Since most modern software systems usually intensively make use of 
		third-party components, it is difficult to provide systems which are
		not built from insustainable parts.
	</problem>
	<solution>
		One approach would be to provide information about the used parts,
		e.g. in the form of "information leaflets", and to assist the software 
		developer when selection decisions about parts have to be made [1]. 
		E.g. an information leaflet could provide information about the 
		electric energy demand of a software component, hardware utilization  
		etc. [2].
	</solution>
	<confidence>Idea</confidence>
	<literature>
	 	<bibliomixed id="1">
			Schmidt, B. (2016): Sustainability Knowledge about Software 
			Parts in Software Engineering Processes. 4th Intern. Conf. on 
			Sustainability (ICT4S).
		</bibliomixed>
		<bibliomixed id="2">
			Umweltbundesamt, eds.: Project REFOPLAN. Berlin: Federal 
			Environment Agency, work in progress.
		</bibliomixed>
 	</literature>
	<formalization language="CafeOBJ">
		<participant identifier="f" type="Func"/>
		<participant identifier="part" type="uml$Component"/>
		<participant identifier="p1" type="Part &lt; uml$Executable"/>
		<participant identifier="p2" type="Part &lt; uml$Executable"/>
		<participant identifier="" type=""/>
		<participant identifier="" type=""/>
		<source-code location="SustainableParts.cafe"/>
	</formalization>
	<related-patterns>
		<pattern-link type="is-related-to" patternID="7" collection="candidates" 
			label="support component replaceability"/>
		<pattern-link type="is-contained-by" 
			patternID="99" collection="candidates" 
			label="raise sustainability awareness"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.3</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>16.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/ComponentReplaceability.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="7" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Component Replaceability</name>
	<alias>Switch Implementation</alias>
	<problem>
		A software system can not be used in sustainable manner or can not be
		used at all, since a known software component does not work.
	</problem>
	<solution>
		Replace the responsible component by a more suitable component. To do
		this, the often the presence of suitable system-internal interfaces is
		a pre-requisiste. 
	</solution>
	<confidence>Idea</confidence>
	<formalization language="">
		<source-code location=""/>
	</formalization>
	<related-patterns>
		<pattern-link type="is-related-to" patternID="5" collection="candidates" 
			label="provide component leaflets"/>
		<pattern-link type="is-related-to" patternID="6" collection="candidates" 
			label="assure backward compatibility"/>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.2</revision-number>
		<creation-date>14.07.2019</creation-date>
		<last-modified>16.07.2019</last-modified>
	</management>
</pattern>

=== bogeo/suspatterns/descriptions/SwitchOffUnneededFeatures.xml
<?xml version="1.0" ?>
<?xml-stylesheet href="../plml/plml_bo-2.0.css"?>
<pattern patternID="11" collection="candidates" 
		xsi:noNamespaceSchemaLocation="../plml/plml_bo-2.0.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Switch Off Unneeded Processes</name>
	<alias>Dynamic Resources</alias>
	<alias>Scaleability</alias>
	<problem>
		The energy consumption of a developed software solution is high due to running 
		process instances that unnecessarily are active with repect to the current requirements. 
		(See [1].)
	</problem>
	<solution>
		Adapt the number of active process instances dynamically with respect to the 
		actual requirements at runtime by adding or removing further instances. Generally,
		such a mechanism has to be considered at an early stage when designing the overall 
		system's architecture.
	</solution>
	<evidence>
		<rationale>
		</rationale>
	</evidence>
	<confidence>reviewed</confidence>
	<literature>
		<bibliomixed id="1">
			Geiger et al. (2020): Ressourceneffiziente Programmierung. Berlin: Bitkom, S. 12. 
		</bibliomixed>
	</literature>
	<related-patterns>
	</related-patterns>
	<management>
		<author>Benno Schmidt</author>
		<revision-number>0.1</revision-number>
		<creation-date>12.05.2021</creation-date>
		<last-modified>12.05.2021</last-modified>
	</management>
</pattern>
